# Schema for the configuration files of the CloudFlare module.
cloudflare.settings:
  type: config_object
  label: 'CloudFlare Config'
  mapping:
    client_ip_restore_enabled:
      label: 'Restore Client Ip Address.'
      type: boolean
      translatable: false
    bypass_host:
      label: 'Host to Bypass CloudFlare.  Helps suppress log warnings regarding requests bypassing CloudFlare.'
      type: string
      translatable: false
    valid_credentials:
      label: 'Indicator that user entered credentials are valid.'
      type: boolean
      translatable: false
    zone_id:
      type: string
      label: 'CloudFlare ZoneId corresponding to the site domain.'
      translatable: false
    credential_provider:
      type: 'string'
      label: 'Credential provider'
    credentials:
      type: sequence
      label: 'Credentials'
      sequence:
        type: cloudflare.credentials.[%key]

cloudflare.credentials.cloudflare:
  type: mapping
  label: 'Cloudflare credentials'
  mapping:
    email:
      type: string
      label: 'Email'
    apikey:
      type: string
      label: 'API Key'

cloudflare.credentials.key:
  type: mapping
  label: 'Cloudflare credentials with Key Module'
  mapping:
    email:
      type: string
      label: 'Email'
    apikey_key:
      type: string
      label: 'API key'

cloudflare.credentials.multikey:
  type: mapping
  label: 'Cloudflare credentials with Key Module (user/password keys)'
  mapping:
    email_apikey_key:
      type: string
      label: 'Email/API key (User/Password)'
